# DATABASE CONFIG
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA CONFIG (IMPORTANT CHANGE)
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.default_schema=kaamsaathi
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# SERVER
server.port=8080

# LOGGING CONFIG (LESS VERBOSE)
logging.level.root=WARN
logging.level.com.kaamsaathi=INFO

logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=OFF

logging.file.name=logs/kaamsaathi.log

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%level] [%logger{20}] %msg%n
spring.output.ansi.enabled=NEVER

# ACTUATOR (SAFE)
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never

info.app.name=KaamSaathi
info.app.version=1.0
info.app.description=Blue collar hiring platform