# DATABASE CONFIG
spring.datasource.url=jdbc:postgresql://localhost:5432/kaamsaathi
spring.datasource.username=postgres
spring.datasource.password=postgres

# JPA CONFIG
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.default_schema=kaamsaathi

# SERVER
server.port=8080


# LOGGING CONFIG
logging.level.root=INFO
logging.level.com.kaamsaathi=DEBUG

# Disable Hibernate SQL noise
logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=OFF

# File logging
logging.file.name=logs/kaamsaathi.log

# Clean log format
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%level] [%logger{20}] %msg%n
spring.output.ansi.enabled=ALWAYS

# ACTUATOR
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

info.app.name=KaamSaathi
info.app.version=1.0
info.app.description=Blue collar hiring platform

